### ISSUE TITLE
能不能加个设置关于搜索结果排序

### ISSUE THREAD

**Issue by mutunx** [chaselen/v2ex-playground#11]
搜索一些时效性很强的关键词时,想进行时间倒序搜索 现在是根据权重排序,经常出现好几年前的贴子,想找最近时间的贴子要翻好久

**Comment by chaselen** [comment]
> 



> 搜索一些时效性很强的关键词时,想进行时间倒序搜索 现在是根据权重排序,经常出现好几年前的贴子,想找最近时间的贴子要翻好久

v1.5.0已经支持
