### ISSUE TITLE
Unable to login with cookie

### ISSUE THREAD

**Issue by erbanku** [chaselen/v2ex-playground#18]
Tried all the cookie values below one by one, but none worked. Can you please help me? I was able to log in about half a year ago.

![image](https://github.com/chaselen/v2ex-playground/assets/79493862/6fce5c96-c8df-41d8-bca4-6e9fda008a84)

**Comment by erbanku** [comment]
Closed as not planned by @erbanku on Tuesday, March 12, 2024

**Comment by chaselen** [comment]
@erbanku You use it in the wrong way. Capture a page request, then copy the `Cookie` header.

**Comment by erbanku** [comment]
> @erbanku You use it in the wrong way. Capture a page request, then copy the `Cookie` header value.

Fixed, thank you.🙃
