### ISSUE TITLE
关于一页数据的问题

### ISSUE THREAD

**Issue by yihong0618** [chaselen/v2ex-playground#3]
作者你好
我才开始玩v2ex，在GitHub上搜索到你的这个vscode插件。感谢你的工作。
![image](https://user-images.githubusercontent.com/15976103/95963888-d0dd7b00-0e3a-11eb-9038-56801c11f48c.png)
因为之前我也做过vscode插件的原因 [vscode-gcores](https://github.com/yihong0618/vscode-gcores)
我曾经做过怎么实现翻页的方案，
是在最后一个tree-node 里扔一个显示更多的node，如下图

![image](https://user-images.githubusercontent.com/15976103/95964407-59f4b200-0e3b-11eb-9cca-4094657f9259.png)

不知道这个方案你感觉可以么？如果可以我可以提一个Pr~

P.S. 谢谢作者

**Comment by chaselen** [comment]
可以啊，我之前也是想这么实现的。欢迎提交pr

**Comment by chaselen** [comment]
ps：上面的截图说的是只加载了一页评论的问题😂，现在已经支持多页评论了哈

**Comment by yihong0618** [comment]
> ps：上面的截图说的是只加载了一页评论的问题😂，现在已经支持多页评论了哈

好的，可能周末或者下周尝试下。

**Comment by yihong0618** [comment]
试了一下，发现v2的逻辑不一样~。
不是按照节点翻页的，
先close了，sorry.
