### ISSUE TITLE
不知道能不能做，希望加个搜索功能栏

### ISSUE THREAD

**Issue by zhang0peter** [chaselen/v2ex-playground#4]
v2用的是谷歌的搜索，希望新增一个搜索栏，输入关键字后就筛选出结果，就可以直接浏览了。

**Comment by chaselen** [comment]
ok，搜索功能在计划中了🥳

**Comment by zhang0peter** [comment]
哇，感谢(￣▽￣)~*

**Comment by chaselen** [comment]
v1.4.2版本已经发布，加上了搜索功能。（位置：首页栏的搜索图标）

**Comment by zhang0peter** [comment]
有2个问题：
1.已经登录了v2ex，还要重新登录。输入cokkie后还是登录失败。
2.希望搜索引擎可以换成谷歌，或者可以自选搜索引擎。我搜牛奶的结果不符合预期，都是很老的帖子。
![image](https://user-images.githubusercontent.com/26668281/96689362-e1e73880-13b4-11eb-9489-582ec356dd3b.png)

**Comment by chaselen** [comment]
谷歌需要翻墙，不能保证一定有些用户用不了呀

**Comment by chaselen** [comment]
cookie是用的请求头里面的吗，自测是没有问题的😂

**Comment by zhang0peter** [comment]
> cookie是用的请求头里面的吗，自测是没有问题的😂

我这边可以复现，搜索牛奶，点蒙牛牛奶的奇怪问题后，登录不了。
![image](https://user-images.githubusercontent.com/26668281/96713203-d30f7e80-13d2-11eb-886b-18f46a9b619e.png)

**Comment by chaselen** [comment]
不是已经登录成功了么，右下角有提示了

**Comment by zhang0peter** [comment]
> 不是已经登录成功了么，右下角有提示了

但点进搜索结果后就变为未登录了。
![image](https://user-images.githubusercontent.com/26668281/96715631-7615c780-13d6-11eb-933d-cebe43b6acca.png)

**Comment by chaselen** [comment]
方便给个cookie试一下？我自己的是没问题的😂

**Comment by zhang0peter** [comment]
> 方便给个cookie试一下？我自己的是没问题的😂

cookie比较敏感，那就算了。搜索引擎换一个吧，换成谷歌。

**Comment by chaselen** [comment]
目前我这里判断登录失效的逻辑是访问帖子的时候是否被重定向（可能是这个原因）。是不是你账号触发什么验证了。在浏览器访问一下这个帖子看看是什么现象

**Comment by zhang0peter** [comment]
谷歌搜不到这个贴。。。
![image](https://user-images.githubusercontent.com/26668281/96719719-5aadbb00-13dc-11eb-9b97-22819cb674a9.png)

![image](https://user-images.githubusercontent.com/26668281/96719774-71541200-13dc-11eb-839d-3c0005ef4ac4.png)

**Comment by chaselen** [comment]
https://www.sov2ex.com，直接在这里搜一下。目前我用的搜索就是用这个api

**Comment by zhang0peter** [comment]
找到原因了。
![image](https://user-images.githubusercontent.com/26668281/96720341-36061300-13dd-11eb-9683-690b70a5f322.png)

**Comment by chaselen** [comment]
看来我得完善一下登录失效的判断逻辑。。

**Comment by chaselen** [comment]
v1.4.3版本完善了访问逻辑。访问受限的帖子会给出提示，并且不会使登录态失效

**Comment by zhang0peter** [comment]
OK，问题解决了。

**Comment by zhang0peter** [comment]
> v1.4.3版本完善了访问逻辑。访问受限的帖子会给出提示，并且不会使登录态失效

再提个建议，用户名现在是蓝色，很显眼，希望可以变为灰色这种不显眼的颜色。

**Comment by zhang0peter** [comment]
> > v1.4.3版本完善了访问逻辑。访问受限的帖子会给出提示，并且不会使登录态失效
> 
> 再提个建议，用户名现在是蓝色，很显眼，希望可以变为灰色这种不显眼的颜色。

以及页面可以加个刷新按钮吗？想刷新页面只能重新搜索打开页面

**Comment by chaselen** [comment]
> 再提个建议，用户名现在是蓝色，很显眼，希望可以变为灰色这种不显眼的颜色。

会考虑微调一下样式，不过这个不能固定，需要跟着主题变化

**Comment by chaselen** [comment]
> 以及页面可以加个刷新按钮吗？想刷新页面只能重新搜索打开页面

可以，后面版本加上

**Comment by chaselen** [comment]
> 以及页面可以加个刷新按钮吗？想刷新页面只能重新搜索打开页面

v1.4.4版本加上了刷新按钮，评论中的用户名去掉了加粗效果，看起来没有那么显眼

**Comment by zhang0peter** [comment]
> > 以及页面可以加个刷新按钮吗？想刷新页面只能重新搜索打开页面
> 
> v1.4.4版本加上了刷新按钮，评论中的用户名去掉了加粗效果，看起来没有那么显眼

看到效果了，感谢大佬
