### ISSUE TITLE
[feature request] 新的页面可以总是在当前 tab 打开

### ISSUE THREAD

**Issue by zoubingwu** [chaselen/v2ex-playground#5]
插件很棒! 不知道别人有没有这个需求，就是希望有个设置项之类的，设置了以后可以每次打开页面都是在同一个 tab 而不是新开一个 tab 打开，因为点多了会开很多个 tab，然后又要一个一个关掉比较麻烦。 🙇

**Comment by chaselen** [comment]
属实是因为懒。。在V1.4.5版本加上这个设置了
设置方式：
`设置-扩展-V2EX Playground`：在新标签页中打开链接

**Comment by chaselen** [comment]
> 插件很棒! 不知道别人有没有这个需求，就是希望有个设置项之类的，设置了以后可以每次打开页面都是在同一个 tab 而不是新开一个 tab 打开，因为点多了会开很多个 tab，然后又要一个一个关掉比较麻烦。 🙇

属实是因为懒。。在V1.4.5版本加上这个设置了
设置方式：
`设置-扩展-V2EX Playground`：在新标签页中打开链接
