### ISSUE TITLE
报了一个错误

### ISSUE THREAD

**Issue by leo95123** [chaselen/v2ex-playground#6]
connect ETIMEDOUT 108.160.167.165:443

**Comment by chaselen** [comment]
> connect ETIMEDOUT 108.160.167.165:443
> 

现在访问v站需要科学上网了

**Comment by leo95123** [comment]
对的，我一直用的浏览器扩展科学上网，所以网页访问一直没问题。昨天用了其他代理，现在已经恢复正常了。谢谢！
