### ISSUE TITLE
无法正常使用

### ISSUE THREAD

**Issue by myth984** [chaselen/v2ex-playground#9]
也加载不出来

也登录不上去 
不知道是不是我自己的问题

![image](https://user-images.githubusercontent.com/43159834/157008160-c790bb2f-cdac-48f0-848c-a2c59f2a3937.png)

**Comment by chaselen** [comment]
> 也加载不出来
> 
> 也登录不上去 不知道是不是我自己的问题
> 
> ![image](https://user-images.githubusercontent.com/43159834/157008160-c790bb2f-cdac-48f0-848c-a2c59f2a3937.png)

需要科学上网
